version: '2'

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.5.0.0/16
        gateway: 172.5.5.254

services:
  music.local:
      container_name: music.local
      hostname: music.local
      image: skyerus/environments:httpd-php73-nodejs
      command: bash -c "npm install && npm run dev"
      volumes:
        - ~/personalweb/music:/app
        - ~/personalweb/music/node_modules:/app/node_modules
        - ~/.composer:/root/.composer
        - ~/.gitconfig:/root/.gitconfig
        - ./log/music:/var/log/music
        - './tools:/tools'
        - './phpsessions:/var/lib/php/session'
        - ~/.docker_bash_history:/root/.bash_history
      ports:
        - '8081:80'
      networks:
        default:
          ipv4_address: 172.5.0.2
      environment:
        - DB_HOST=mysql.music.local
        - APP_ENV=local
        - VOLUME=/app
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_GROUP=${DOCKER_GROUP}
        - HOST_USER_ID=${HOST_USER_ID}
        - HOST_GROUP_ID=${HOST_GROUP_ID}
        - PHP_IDE_CONFIG=serverName=music.local
        - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
