version: '2'

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.5.0.0/16
        gateway: 172.5.5.254

volumes:
  mysql.local:

services:
  music.local:
      container_name: music.local
      hostname: music.local
      image: skyerus/environments:httpd-centos7-php73-nodejs
#      command: bash -c "npm install && npm run build && /usr/sbin/httpd -D FOREGROUND"
      command: bash -c "npm install && npm run dev"
      volumes:
        - ~/personalweb/music:/app
        - ~/personalweb/music/node_modules:/app/node_modules
        - ~/.composer:/root/.composer
        - ~/.gitconfig:/root/.gitconfig
        - ./log/music:/var/log/music
        - './tools:/tools'
        - './phpsessions:/var/lib/php/session'
        - ~/.docker_bash_history:/root/.bash_history
      ports:
        - '8080:80'
      networks:
        default:
          ipv4_address: 172.5.0.2
      environment:
        - DB_HOST=mysql.music.local
        - APP_ENV=local
        - VOLUME=/app
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_GROUP=${DOCKER_GROUP}
        - HOST_USER_ID=${HOST_USER_ID}
        - HOST_GROUP_ID=${HOST_GROUP_ID}
        - PHP_IDE_CONFIG=serverName=music.local
        - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
        - HOST=0.0.0.0
        - PORT=80

  neo4j.local:
      container_name: neo4j.local
      hostname: neo4j.local
      image: neo4j:latest
      volumes:
        - ~/personalweb/neo4j/data:/data
      ports:
        - '7474:7474'
      networks:
        default:
          ipv4_address: 172.5.0.3
      environment:
        - NEO4J_ROOT_USER=neo4j
        - NEO4J_ROOT_PASSWORD=8nzWEfNJL81z

  mysql.local:
    container_name: mysql.local
    hostname: mysql.local
    image: skyerus/environments:mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql.local:/var/lib/mysql"
      - ~/.docker_bash_history:/root/.bash_history
    networks:
      default:
        aliases:
          - mysql.music.local
        ipv4_address: 172.5.0.4
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=music
      - MYSQL_USER=music
      - MYSQL_PASSWORD=music
      - MYSQL_DATABASE=MUSIC

  music-api.local:
    container_name: music-api.local
    hostname: music-api.local
    image: skyerus/environments:httpd-centos7-php73
    volumes:
      - ~/personalweb/music-api:/app
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/music-api/app:/var/log/music-api/app
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    ports:
      - '8081:80'
    networks:
      default:
        ipv4_address: 172.5.0.5
    environment:
      - DB_HOST=mysql.music.local
      - APP_ENV=dev
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=music-api.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
      - HOST=0.0.0.0
      - PORT=80
