version: '3.5'

networks:
  riptides:
    name: riptides_network

volumes:
  mysql.rip.local:
  redis.local:
  jenkins_home:

services:
#  riptides-api.local:
#      container_name: riptides-api.local
#      hostname: riptides-api.local
#      image: skyerus/environments:nginx-api
#      ports:
#        - '8080:80'
#      networks:
#        - riptides
#      environment:
#        - PHP_FPM_HOST=php73-api
#      command: /bin/bash -c "envsubst '$$PHP_FPM_HOST' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


#  riptides-api.local:
#    container_name: riptides-api.local
#    hostname: riptides-api.local
#    image: skyerus/environments:nginx-api
#    ports:
#      - '8080:80'
#    networks:
#      - riptides
#    environment:
#      - PHP_FPM_HOST=php73-api
#    command: /bin/bash -c "envsubst '$$PHP_FPM_HOST' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

#  php73-api:
#    container_name: php73-api
#    image: skyerus/environments:php73-fpm
#    volumes:
#      - ~/web/riptides-api:/app
#      - ~/.composer:/root/.composer
#      - ~/.gitconfig:/root/.gitconfig
#      - ./log/riptides-api/app:/var/log/riptides-api/app
#      - './phpsessions:/var/lib/php/session'
#      - ~/.docker_bash_history:/root/.bash_history
#    networks:
#      - riptides
#    environment:
#      - DB_HOST=mysql.riptides.local
#      - APP_ENV=dev
#      - VOLUME=/app
#      - DOCKER_USER=${DOCKER_USER}
#      - DOCKER_GROUP=${DOCKER_GROUP}
#      - HOST_USER_ID=${HOST_USER_ID}
#      - HOST_GROUP_ID=${HOST_GROUP_ID}
#      - PHP_IDE_CONFIG=serverName=riptides-api.local
#      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
#      - HOST=0.0.0.0
#      - PORT=80

  riptides-api.local:
    container_name: riptides-api.local
    hostname: riptides-api.local
    image: skyerus/environments:riptides-go
    command: bash -c "tail -f /dev/null"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ~/go/src:/go/src
    ports:
      - '8080:80'
      - '40000:40000'

  riptides.local:
    container_name: riptides.local
    hostname: riptides.local
#    image: skyerus/environments:nginx-static
    image: skyerus/environments:node-alpine
    command: bash -c "npm install && npm run dev"
    volumes:
      - ~/web/riptides:/app
      - ~/web/riptides/node_modules:/app/node_modules
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/riptides:/var/log/riptides
      - './tools:/tools'
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    ports:
      - '8081:80'
    networks:
      - riptides
    environment:
      - APP_ENV=local
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=riptides.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0

  mysql.riptides.local:
    container_name: mysql.riptides.local
    hostname: mysql.riptides.local
    image: skyerus/environments:mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql.rip.local:/var/lib/mysql"
      - ~/.docker_bash_history:/root/.bash_history
    networks:
      - riptides
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=riptides
      - MYSQL_USER=riptides
      - MYSQL_PASSWORD=riptides
      - MYSQL_DATABASE=riptides

  chat-socket.local:
    container_name: chat-socket.local
    hostname: chat-socket.local
    image: skyerus/environments:node-alpine
    #    command: bash -c "npm install && npm start"
    command: bash -c "tail -f /dev/null"
    volumes:
      - ~/web/chat-socket:/app
      - ~/web/chat-socket/node_modules:/app/node_modules
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/chat-socket:/var/log/chat-socket
      - './tools:/tools'
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    ports:
      - '8082:80'
    networks:
      - riptides
    environment:
      - APP_ENV=local
      - RIPTIDES_API_HOST=http://riptides-api.local/
      - RIPTIDES_HOST=http://riptides.local
      - DEBUG=express:*
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=chat-socket.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
      - HOST=0.0.0.0
      - PORT=80

  redis.local:
    container_name: redis.local
    hostname: redis.local
    image: redis:5.0.4
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis.local:/data
    networks:
      - riptides
    ports:
      - '8083:6379'

  jenkins.local:
    container_name: jenkins.local
    hostname: jenkins.local
    image: skyerus/environments:jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - riptides
    ports:
      - '8084:8080'
      - '50000:50000'


#  chat-socket.local:
#    container_name: chat-socket.local
#    hostname: chat-socket.local
#    image: eu.gcr.io/riptides/chat-socket@sha256:a1db319c74c5830f36c2f8927620387cc1e9dd0a76290a556b28de0c9f7ff90d
#    ports:
#      - '8082:80'
#    volumes:
#      - ~/web/chat-socket/key/public.pem:/app/key/public.pem
#    networks:
#      - riptides
#    environment:
#      - APP_ENV=local
#      - RIPTIDES_API_HOST=http://riptides-api.local/
#      - RIPTIDES_HOST=http://riptides.local
#      - DEBUG=express:*
#      - MYSQL_HOST=mysql.riptides.local
#      - MYSQL_DATABASE=riptides
#      - MYSQL_USER=riptides
#      - MYSQL_PASSWORD=riptides
#      - REDIS_HOST=redis.local
#      - REDIS_PORT=6379
#      - VOLUME=/app
#      - DOCKER_USER=${DOCKER_USER}
#      - DOCKER_GROUP=${DOCKER_GROUP}
#      - HOST_USER_ID=${HOST_USER_ID}
#      - HOST_GROUP_ID=${HOST_GROUP_ID}
#      - PHP_IDE_CONFIG=serverName=chat-socket.local
#      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
#      - HOST=0.0.0.0
#      - PORT=80

#  php73-api:
#    container_name: php73-api
#    image: eu.gcr.io/riptides/api@sha256:d9c30d3bf63ff0da27596116c7bdc52972dbacc7d122a66575b057d461c5c82a
#    volumes:
#      - ~/web/riptides-api/config/jwt/private.pem:/app/config/jwt/private.pem
#      - ~/web/riptides-api/config/jwt/public.pem:/app/config/jwt/public.pem
#    networks:
#      - riptides
#    environment:
#      - DB_HOST=mysql.riptides.local:3306
#      - DB_USER=riptides
#      - DB_PASSWORD=riptides
#      - DB_NAME=riptides
#      - APP_ENV=prod
#      - CHAT_SOCKET_URL=http://chat-socket.local
#      - SPOTIFY_CLIENT_ID=d3c7e6a9b7754c93975021c666579dff
#      - SPOTIFY_CLIENT_SECRET=71abaf0bd46d4ccb838a8ce0a90a737f
#      - SPOTIFY_REDIRECT_URI=http://riptides.local/settings
#      - JWT_MY_SECRET_KEY=/app/config/jwt/private.pem
#      - JWT_MY_PUBLIC_KEY=/app/config/jwt/public.pem
#      - JWT_MY_PASSPHRASE=riptides-api
#      - VOLUME=/app
#      - CORS_ALLOW_ORIGIN=^https?://riptides.local(:[0-9]+)?$$
#      - APP_SECRET=7e3ece4540f94b5d8919e1d91a2d846f
