version: '3.5'

networks:
  riptides:
    name: riptides_network

volumes:
  mysql.rip.local:
  redis.local:
  jenkins_home:

services:
  riptides-api.local:
    container_name: riptides-api.local
    hostname: riptides-api.local
    image: skyerus/environments:nginx-api
    ports:
      - '8080:80'
    networks:
      - riptides
    environment:
      - PHP_FPM_HOST=php73-api
    command: /bin/bash -c "envsubst '$$PHP_FPM_HOST' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  php73-api:
    container_name: php73-api
    image: skyerus/environments:php73-fpm
    volumes:
      - ~/personalweb/riptides-api:/app
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/riptides-api/app:/var/log/riptides-api/app
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    networks:
      - riptides
    environment:
      - DB_HOST=mysql.riptides.local
      - APP_ENV=dev
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=riptides-api.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
      - HOST=0.0.0.0
      - PORT=80

  riptides.local:
    container_name: riptides.local
    hostname: riptides.local
#    image: skyerus/environments:nginx-static
    image: skyerus/environments:node-alpine
    command: bash -c "npm install && npm run dev"
    volumes:
      - ~/personalweb/riptides:/app
      - ~/personalweb/riptides/node_modules:/app/node_modules
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/riptides:/var/log/riptides
      - './tools:/tools'
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    ports:
      - '8081:80'
    networks:
      - riptides
    environment:
      - APP_ENV=local
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=riptides.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0

  mysql.riptides.local:
    container_name: mysql.riptides.local
    hostname: mysql.riptides.local
    image: skyerus/environments:mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql.rip.local:/var/lib/mysql"
      - ~/.docker_bash_history:/root/.bash_history
    networks:
      - riptides
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=riptides
      - MYSQL_USER=riptides
      - MYSQL_PASSWORD=riptides
      - MYSQL_DATABASE=riptides

  chat-socket.local:
    container_name: chat-socket.local
    hostname: chat-socket.local
    image: skyerus/environments:node-alpine
    #    command: bash -c "npm install && npm start"
    command: bash -c "tail -f /dev/null"
    volumes:
      - ~/personalweb/chat-socket:/app
      - ~/personalweb/chat-socket/node_modules:/app/node_modules
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ./log/chat-socket:/var/log/chat-socket
      - './tools:/tools'
      - './phpsessions:/var/lib/php/session'
      - ~/.docker_bash_history:/root/.bash_history
    ports:
      - '8082:80'
    networks:
      - riptides
    environment:
      - APP_ENV=local
      - RIPTIDES_API_HOST=http://riptides-api.local/
      - RIPTIDES_HOST=http://riptides.local
      - DEBUG=express:*
      - VOLUME=/app
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_GROUP=${DOCKER_GROUP}
      - HOST_USER_ID=${HOST_USER_ID}
      - HOST_GROUP_ID=${HOST_GROUP_ID}
      - PHP_IDE_CONFIG=serverName=chat-socket.local
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=${HOST_ADDRESS} profiler_enabled=0 remote_connect_back=0
      - HOST=0.0.0.0
      - PORT=80

  redis.local:
    container_name: redis.local
    hostname: redis.local
    image: redis:5.0.4
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis.local:/data
    networks:
      - riptides
    ports:
      - '8083:6379'

  jenkins.local:
    container_name: jenkins.local
    hostname: jenkins.local
    image: skyerus/environments:jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - riptides
    ports:
      - '8084:8080'
      - '50000:50000'
