#!/usr/bin/env bash
#https://github.com/schmidigital/permission-fix
set -e


echo "Setting permissions for the docker container..."
/tools/permission_fix || true
chown -R $DOCKER_USER:$DOCKER_GROUP $VOLUME || true
echo "Done."

chown apache:apache /var/data -R
chown apache:apache /var/log -R

/usr/sbin/httpd -D FOREGROUND
